# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\hly_project\OpenGL-with-Emscripten

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\hly_project\OpenGL-with-Emscripten

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\msys64\mingw64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\hly_project\OpenGL-with-Emscripten\CMakeFiles D:\hly_project\OpenGL-with-Emscripten\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\hly_project\OpenGL-with-Emscripten\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named emscripten_test_2

# Build rule for target.
emscripten_test_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 emscripten_test_2
.PHONY : emscripten_test_2

# fast build rule for target.
emscripten_test_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\emscripten_test_2.dir\build.make CMakeFiles/emscripten_test_2.dir/build
.PHONY : emscripten_test_2/fast

#=============================================================================
# Target rules for targets named Operator_OverLoading

# Build rule for target.
Operator_OverLoading: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Operator_OverLoading
.PHONY : Operator_OverLoading

# fast build rule for target.
Operator_OverLoading/fast:
	$(MAKE) $(MAKESILENT) -f lib\05_dir\CMakeFiles\Operator_OverLoading.dir\build.make lib/05_dir/CMakeFiles/Operator_OverLoading.dir/build
.PHONY : Operator_OverLoading/fast

src/guessing.o: src/guessing.cpp.o

.PHONY : src/guessing.o

# target to build an object file
src/guessing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\emscripten_test_2.dir\build.make CMakeFiles/emscripten_test_2.dir/src/guessing.cpp.o
.PHONY : src/guessing.cpp.o

src/guessing.i: src/guessing.cpp.i

.PHONY : src/guessing.i

# target to preprocess a source file
src/guessing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\emscripten_test_2.dir\build.make CMakeFiles/emscripten_test_2.dir/src/guessing.cpp.i
.PHONY : src/guessing.cpp.i

src/guessing.s: src/guessing.cpp.s

.PHONY : src/guessing.s

# target to generate assembly for a file
src/guessing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\emscripten_test_2.dir\build.make CMakeFiles/emscripten_test_2.dir/src/guessing.cpp.s
.PHONY : src/guessing.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Operator_OverLoading
	@echo ... emscripten_test_2
	@echo ... src/guessing.o
	@echo ... src/guessing.i
	@echo ... src/guessing.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

